
# make sure tyou have setup cocotb env and sourced it 
# Makefile
TOPLEVEL_LANG = verilog
VERILOG_SOURCES = axil_adapter.v axil_rd_adapter.v axil_wr_adapter.v
TOPLEVEL = axil_adapter
MODULE = test_axil_adapter
SIM ?= icarus

include [PATH]/Makefile.sim

# the path above is to be filled by adding the path to Makefile found in the cocotb-env ,teh file will be called Makefile_sim mine was below 
# /home/ojaskudari/Desktop/cocotb/cocotbext-axi/cocotb-env/lib/python3.12/site-packages/cocotb/share/makefiles/Makefile.sim

